spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379